### ISSUE TITLE
How complete is this? :)

### ISSUE THREAD

**Issue by robertherber** [marcesengel/zod-to-mongodb-schema#1]
Thanks a lot for creating this package @marcesengel! This is one of the main things I'm looking for when looking to add zod to our tech stack. We're currently using GraphQL with Codegen as a base with additional TypeScript typings towards MongoDB, but being able to use MongoDBs Schema Validation would be really nice.

Noting this is a new package, how complete do you consider it?

**Comment by marcesengel** [comment]
Hi @robertherber, thanks for asking!

I've just [added a support matrix to the README](https://github.com/marcesengel/zod-to-mongodb-schema#supported-validators) due to your request. Note however that the npm package isn't up-to-date. In case the current feature set is interesting to you, I can easily publish it - just let me know.
I'll publish `1.0.0` once validator coverage is acceptable from my POV (roughly meaning support for unions, tuples, records, literals, enums and lazy).

Right now only the very basics are supported, I'm open to PRs for anything which currently is WIP (just make sure to tell if you'd like to work on something, so it isn't done twice 😉). The code is very straight forward and you can easily add test cases for anything by just declaring them in an array.

My plan is to get this done in the next two weeks 👍 we are also planning to use it soon and honestly this stuff is fairly straightforward.

**Comment by robertherber** [comment]
Thanks, that helps a lot!

Will start playing around with Zod a bit over the next few weeks - will probably gradually move over to this!

Feel free to close this - I think the support matrix is what I was really looking for 🙂
